
1 GPUs available:
GPU 0: NVIDIA GeForce RTX 3080 Laptop GPU, Free Memory: 15.81 GB
Using device: cuda:0, with 15.81 GB free memory
Skipping Angle = 90 degrees
GPU with free memory: 15.08 GB and with optimal batch size: 132.0
Now using device: cuda:0 with optimal batch size: 132
Estimated Memory Requirement for the Batch Size: 14.96 GB
Estimated Memory Requirement for the Full Size: 191502.83 GB
IP Address: 10.0.90.194
Using batches with forced batch size: 8192 with Estimated Memory: 928.3121557980776 GB
continuing from last checkpoint...
Traceback (most recent call last):
  File "C:\Users\ameir\Dropbox\School\Graduate\CERN\Scripts\PINNs\current\config_14102023_adam_datalosscontloss_infinite_master_0.py", line 93, in <module>
    main(base_directory, config, output_zip_file)
  File "C:\Users\ameir\Dropbox\School\Graduate\CERN\Scripts\PINNs\current\main.py", line 41, in main
    model = train_model(model, device, X_train_tensor, y_train_tensor, config, batch_size, model_file_path, epochs=config["epochs"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameir\Dropbox\School\Graduate\CERN\Scripts\PINNs\current\training.py", line 137, in train_model
    model.load_state_dict(modified_state_dict)
  File "C:\Users\ameir\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DistributedDataParallel:
        Missing key(s) in state_dict: "module.fc1.weight", "module.fc1.bias", "module.fc2.weight", "module.fc2.bias", "module.fc3.weight", "module.fc3.bias", "module.fc4.weight", "module.fc4.bias", "module.stress_tensor_layer.weight", "module.stress_tensor_layer.bias", "module.output_layer.weight", "module.output_layer.bias".
        Unexpected key(s) in state_dict: "module.module.fc1.weight", "module.module.fc1.bias", "module.module.fc2.weight", "module.module.fc2.bias", "module.module.fc3.weight", "module.module.fc3.bias", "module.module.fc4.weight", "module.module.fc4.bias", "module.module.stress_tensor_layer.weight", "module.module.stress_tensor_layer.bias", "module.module.output_layer.weight", "module.module.output_layer.bias".



1 GPUs available:
GPU 0: NVIDIA GeForce RTX 3080 Laptop GPU, Free Memory: 13.10 GB
Using device: cuda:0, with 13.10 GB free memory
Skipping Angle = 90 degrees
GPU with free memory: 12.83 GB and with optimal batch size: 112.0
Now using device: cuda:0 with optimal batch size: 112
Estimated Memory Requirement for the Batch Size: 12.69 GB
Estimated Memory Requirement for the Full Size: 191502.83 GB
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [AMEIR]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [AMEIR]:29500 (system error: 10049 - The requested address is not valid in its context.).


1 GPUs available:
GPU 0: NVIDIA GeForce RTX 3080 Laptop GPU, Free Memory: 13.10 GB
Using device: cuda:0, with 13.10 GB free memory
Skipping Angle = 90 degrees
GPU with free memory: 12.83 GB and with optimal batch size: 112.0
Now using device: cuda:0 with optimal batch size: 112
Estimated Memory Requirement for the Batch Size: 12.69 GB
Estimated Memory Requirement for the Full Size: 191502.83 GB

Pinging 10.0.90.194 with 32 bytes of data:
Reply from 10.0.90.194: bytes=32 time=42ms TTL=128
Reply from 10.0.90.194: bytes=32 time=36ms TTL=128
Reply from 10.0.90.194: bytes=32 time=64ms TTL=128
Reply from 10.0.90.194: bytes=32 time=4ms TTL=128

Ping statistics for 10.0.90.194:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 4ms, Maximum = 64ms, Average = 36ms
10.0.90.194 is reachable
RANK: 1
WORLD_SIZE: 2
MASTER_ADDR: 10.0.90.194
MASTER_PORT: 29500
Ok.

[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [AMEIR]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [AMEIR]:29500 (system error: 10049 - The requested address is not valid in its context.).

1 GPUs available:
GPU 0: NVIDIA GeForce RTX 3080 Laptop GPU, Free Memory: 12.83 GB
Using device: cuda:0, with 12.83 GB free memory
Skipping Angle = 90 degrees
GPU with free memory: 12.55 GB and with optimal batch size: 110.0
Now using device: cuda:0 with optimal batch size: 110
Estimated Memory Requirement for the Batch Size: 12.47 GB
Estimated Memory Requirement for the Full Size: 191502.83 GB

Pinging 10.0.90.194 with 32 bytes of data:
Reply from 10.0.90.194: bytes=32 time=5ms TTL=128
Reply from 10.0.90.194: bytes=32 time=5ms TTL=128
Reply from 10.0.90.194: bytes=32 time=4ms TTL=128
Reply from 10.0.90.194: bytes=32 time=4ms TTL=128

Ping statistics for 10.0.90.194:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 4ms, Maximum = 5ms, Average = 4ms
10.0.90.194 is reachable
Service is running on 10.0.90.194:29500
RANK: 1
WORLD_SIZE: 2
MASTER_ADDR: 10.0.90.194
MASTER_PORT: 29500
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [AMEIR]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [AMEIR]:29500 (system error: 10049 - The requested address is not valid in its context.).


1 GPUs available:
GPU 0: NVIDIA GeForce RTX 3080 Laptop GPU, Free Memory: 15.81 GB
Using device: cuda:0, with 15.81 GB free memory
Skipping Angle = 90 degrees
GPU with free memory: 15.08 GB and with optimal batch size: 132.0
Now using device: cuda:0 with optimal batch size: 132
Estimated Memory Requirement for the Batch Size: 14.96 GB
Estimated Memory Requirement for the Full Size: 191502.83 GB
Running on machine with hostname: ameir
Hostname ameir resolved to IP: 10.0.90.194
Ok.

RANK: 0
WORLD_SIZE: 2
MASTER_ADDR: 10.0.90.194
MASTER_PORT: 29500
[W socket.cpp:663] [c10d] The client socket has failed to connect to [ameir.local.local]:29500 (system error: 10049 - The requested address is not valid in its context.).

1 GPUs available:
GPU 0: NVIDIA GeForce RTX 3080 Laptop GPU, Free Memory: 15.08 GB
Using device: cuda:0, with 15.08 GB free memory
Skipping Angle = 90 degrees
GPU with free memory: 14.36 GB and with optimal batch size: 126.0
Now using device: cuda:0 with optimal batch size: 126
Estimated Memory Requirement for the Batch Size: 14.28 GB
Estimated Memory Requirement for the Full Size: 191502.83 GB
Running on machine with hostname: ameir
Hostname ameir resolved to IP: 10.0.90.194
The requested operation requires elevation (Run as administrator).

RANK: 0
WORLD_SIZE: 2
MASTER_ADDR: 10.0.90.194
MASTER_PORT: 29500
[W socket.cpp:436] [c10d] The server socket has failed to bind to [ameir]:29500 (system error: 10048 - Only one usage of each socket address (protocol/network address/port) is normally permitted.).
[W socket.cpp:436] [c10d] The server socket has failed to bind to ameir:29500 (system error: 10013 - An attempt was made to access a socket in a way forbidden by its access permissions.).
[E socket.cpp:472] [c10d] The server socket has failed to listen on any local network address.
Traceback (most recent call last):
  File "C:\Users\ameir\Dropbox\School\Graduate\CERN\Scripts\PINNs\current\config_14102023_adam_datalosscontloss_infinite_master_0.py", line 93, in <module>
    main(base_directory, config, output_zip_file)
  File "C:\Users\ameir\Dropbox\School\Graduate\CERN\Scripts\PINNs\current\main.py", line 41, in main
    model = train_model(model, device, X_train_tensor, y_train_tensor, config, batch_size, model_file_path, log_folder, epochs=config["epochs"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameir\Dropbox\School\Graduate\CERN\Scripts\PINNs\current\training.py", line 53, in train_model
    dist.init_process_group(backend=backend, init_method='env://')  # Use NCCL for GPU communication
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameir\anaconda3\Lib\site-packages\torch\distributed\c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameir\anaconda3\Lib\site-packages\torch\distributed\distributed_c10d.py", line 1141, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameir\anaconda3\Lib\site-packages\torch\distributed\rendezvous.py", line 241, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameir\anaconda3\Lib\site-packages\torch\distributed\rendezvous.py", line 172, in _create_c10d_store
    return TCPStore(
           ^^^^^^^^^
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [ameir]:29500 (system error: 10048 - Only one usage of each socket address (protocol/network address/port) is normally permitted.). The server socket has failed to bind to ameir:29500 (system error: 10013 - An attempt was made to access a socket in a way forbidden by its access permissions.).

1 GPUs available:
GPU 0: NVIDIA GeForce RTX 3080 Laptop GPU, Free Memory: 15.81 GB
Using device: cuda:0, with 15.81 GB free memory
Skipping Angle = 90 degrees
GPU with free memory: 15.08 GB and with optimal batch size: 132.0
Now using device: cuda:0 with optimal batch size: 132
Estimated Memory Requirement for the Batch Size: 14.96 GB
Estimated Memory Requirement for the Full Size: 191502.83 GB
Running on machine with hostname: ameir
Hostname ameir resolved to IP: 10.0.90.194
Found available port: 29000
Ok.

RANK: 0
WORLD_SIZE: 2
MASTER_ADDR: 10.0.90.194
MASTER_PORT: 29000
[W socket.cpp:663] [c10d] The client socket has failed to connect to [ameir.local.local]:29000 (system error: 10049 - The requested address is not valid in its context.).

fe80::ebf1:4947:d87f:a6e2%15


Skipping Angle = 90 degrees
GPU with free memory: 14.36 GB and with optimal batch size: 126.0
Now using device: cuda:0 with optimal batch size: 126
Estimated Memory Requirement for the Batch Size: 14.28 GB
Estimated Memory Requirement for the Full Size: 191502.83 GB
Traceback (most recent call last):
  File "C:\Users\ameir\Dropbox\School\Graduate\CERN\Scripts\PINNs\current\config_14102023_adam_datalosscontloss_infinite_master_0.py", line 93, in <module>
    main(base_directory, config, output_zip_file)
  File "C:\Users\ameir\Dropbox\School\Graduate\CERN\Scripts\PINNs\current\main.py", line 41, in main
    model = train_model(model, device, X_train_tensor, y_train_tensor, config, batch_size, model_file_path, log_folder, epochs=config["epochs"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameir\Dropbox\School\Graduate\CERN\Scripts\PINNs\current\training.py", line 90, in train_model
    dist.init_process_group(backend=backend, init_method=init_method, rank=rank, world_size=world_size)
  File "C:\Users\ameir\anaconda3\Lib\site-packages\torch\distributed\c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameir\anaconda3\Lib\site-packages\torch\distributed\distributed_c10d.py", line 1138, in init_process_group
    rendezvous_iterator = rendezvous(
                          ^^^^^^^^^^^
  File "C:\Users\ameir\anaconda3\Lib\site-packages\torch\distributed\rendezvous.py", line 98, in rendezvous
    return _rendezvous_helper(url, rank, world_size, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameir\anaconda3\Lib\site-packages\torch\distributed\rendezvous.py", line 84, in _rendezvous_helper
    raise RuntimeError(f"No rendezvous handler for {result.scheme}://")
RuntimeError: No rendezvous handler for c://
Press any key to continue . . .


C:\Users\ameir\Dropbox\School\Graduate\CERN\Scripts\PINNs\current

\\192.168.1.1\Users\ameir\Dropbox\School\Graduate\CERN\Scripts\PINNs\current

\\192.168.1.1\Users\ameir\Dropbox\School\Graduate\CERN\Temp_Files\nonlineardynamics\ameir_PINNs\cylinder_cell\14102023_adam_datalosscontloss_infinite\analyses_output\log_output
